name: task_manager
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  auto_route: ^7.8.3
  cloud_firestore: ^4.9.2
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+5
  flutter_screenutil: ^5.9.0
  get_it: ^7.6.4
  google_fonts: ^6.0.0
  hive_flutter: ^1.1.0
  logging: ^1.2.0
  mobx: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0
  auto_route_generator: ^7.3.1
  

flutter:
  uses-material-design: true

  
